---
title: "test_knit"
author: "Yunan Chen"
date: "2024-11-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
# data manipulation
library(dplyr)
library(tidyr)
library(mice)
library(caret)

# summary tables
library(kableExtra)
library(gtsummary)
library(gt)

# interaction plots
library(ggplot2)
library(ggpubr)
library(ggExtra)
library(ggcorrplot)
library(lubridate)
library(ggridges)

# model
# library(lme4)
library(glmnet)

# Plot
library(pROC)

```

```{r}
project2 <- read.csv("~/Desktop/PHP 2550/Data/project2.csv")

# Modify the class of variables 
## Binary
project2$sex_ps <- ifelse(project2$sex_ps == 1, 0, 1)
binary_vars <- sapply(project2, function(x) {
  unique_vals <- unique(x[!is.na(x)])
  (all(unique_vals %in% c(0, 1)) | all(unique_vals %in% c(1, 2))) & is.numeric(x)
})
project2[binary_vars] <- lapply(project2[binary_vars], function(x) as.factor(x))
## Ordinal
project2 <- project2 %>% 
  mutate(edu = factor(edu, levels = 1:5,
                 labels = c("Grade school", "Some high school", "High school graduate or GED",
                            "Some college/technical school", "College graduate"), ordered = TRUE),
         inc = factor(inc, levels = 1:5,
                 labels = c("Less than $20,000", "$20,000–35,000", "$35,001–50,000",
                            "$50,001–75,000", "More than $75,000"), ordered = TRUE))
```

## Summary Table
```{r out.width="60%", fig.align="center"}
# Create a new columns to classify treatment groups and races, re-level categorical variables
project2 <-  project2 %>%
  mutate(Group = case_when(Var == 0 & BA == 0 ~ "ST + placebo", Var == 0 & BA == 1 ~ "BASC + placebo",
                           Var == 1 & BA == 0 ~ "ST + varenicline", Var == 1 & BA == 1 ~ "BASC + varenicline"),
         Race = case_when(Black == 1 & Hisp == 0 & NHW == 0 ~ "Balck",
                          Hisp == 1 & Black == 0 & NHW == 0 ~ "Hispanic",
                          NHW == 1 & Black == 0 & Hisp == 0 ~ "White",
                          Black == 1 & Hisp == 1 & NHW == 0 ~ "Balck and Hispanic",
                          Black == 0 & Hisp == 0 & NHW == 0 ~ "Unknow")) %>% 
  mutate(Group = factor(Group, levels = c("ST + placebo", "BASC + placebo", "ST + varenicline", "BASC + varenicline")),
         Race = factor(Race, levels = c("Balck", "Hispanic", "White", "Balck and Hispanic", "Unknow")))


# Create summary table using tbl_summary
summary_table <- project2 %>%
  select(-c(id, Var, BA, Black, Hisp, NHW)) %>%
  tbl_summary(
    by = Group,  # Group by the treatment groups
    type = list(readiness ~ "continuous"),
    statistic = list(all_continuous() ~ "{mean} ({sd})",  # Mean (SD) for continuous variables
                     all_categorical() ~ "{n} ({p}%)"),    # n (%) for categorical variables
    digits = all_continuous() ~ 1                          # Rounding to 1 decimal place for continuous
  ) %>%
  add_overall() %>%
  modify_header(label = "**Characteristic**") %>%
  bold_labels() %>%  # Convert to gt object for styling
  as_gt() %>% 
  tab_options(
    table.font.size = px(10)  # Set font size to 12px
  ) %>% 
  cols_width(
    everything() ~ px(100),                # Set default column width to 100px
    vars(label) ~ px(150),                 # Set specific width for the label column
    starts_with("stat_") ~ px(120)         # Set specific width for columns starting with "stat_" (summary statistics)
  )

# Display the summary table
summary_table
```

## Variable Distribution and Transformation
```{r out.width="80%", fig.align="center"}
# Apply log transformations to the specified variables
project2 <- project2 %>%
  mutate(hedonsum_n_pq1_log = log(hedonsum_n_pq1 + 1),
         hedonsum_y_pq1_log = log(hedonsum_y_pq1 + 1),
         NMR_log = log(NMR + 1))

vars_trans <- list("hedonsum_n_pq1", "hedonsum_y_pq1", "NMR",
                   "hedonsum_n_pq1_log", "hedonsum_y_pq1_log", "NMR_log")
vars_name_trans <- list("hedonsum_n_pq1" = "Substitute Reinforcers",
                        "hedonsum_y_pq1" = "Complementary Reinforcers",
                        "NMR" = "Nicotine Metabolism Ratio",
                        "hedonsum_n_pq1_log" = "log (Substitute Reinforcers)",
                        "hedonsum_y_pq1_log" = "log (Complementary Reinforcers)",
                        "NMR_log" = "log (Nicotine Metabolism Ratio)")

plot_list <- list()
for (var in vars_trans) {
  var_name <- vars_name_trans[[var]]
  plot <- ggplot(project2, aes_string(x = var)) +
    geom_histogram(bins = 30, color = "black", fill = "lightblue") +
    labs(x = var_name, y = "Frequency") +
    theme_minimal() +
    theme(
      plot.title = element_text(size = 8),
      axis.title = element_text(size = 8),  
      axis.text = element_text(size = 8))
  plot_list[[var]] <- plot
}

plot_trans <- ggarrange(plot_list[["hedonsum_n_pq1"]],
                        plot_list[["hedonsum_n_pq1_log"]],
                        plot_list[["hedonsum_y_pq1"]],
                        plot_list[["hedonsum_y_pq1_log"]],
                        plot_list[["NMR"]], plot_list[["NMR_log"]], 
                        ncol=2, nrow=3)
annotate_figure(plot_trans,
                top = text_grob("Variable Distribution Before and After Log Transformations", face = "bold", size = 10))
```

```{r out.width="90%", fig.align="center"}
# Prepare data by selecting binary variables and reshaping to long format
project2_bi_summary <- na.omit(project2) %>%
  select(abst, sex_ps, ftcd.5.mins, otherdiag, antidepmed, mde_curr, Only.Menthol, Group) %>%
  pivot_longer(
    cols = -c(abst, Group),
    names_to = "Variable",
    values_to = "Value"
  ) %>%
  group_by(Group, Variable, Value) %>%
  summarize(sum_abst = sum(as.numeric(abst)), .groups = "drop") %>%
  arrange(Group, Variable, Value)

# Create the plot
ggplot(data = project2_bi_summary, aes(x = Variable, y = sum_abst, fill = Group, alpha = as.factor(Value))) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = c("#F4BE85", "#F1CE75", "#B2D1E8", "#B2E8B2"), name = "Group") +
  scale_alpha_manual(values = c("0" = 0.5, "1" = 1), guide = "none") +  # Adjust alpha for Value
  coord_flip() +  # Flip coordinates for horizontal layout
  labs(
    x = "Binary Variables",
    y = "Number of Smoking Abstinence",
    title = "Sum of Smoking Abstinence by Group and Binary Variable Levels"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    legend.title = element_text(size = 10)
  )
```